name: Build On Demand

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional tag for the Docker image'
        required: false
        default: ''
        type: string

jobs:
  build:
    uses: ./.github/workflows/routine-buildimage.yml
    with:
      tag: ${{ inputs.tag }}
      cr-namespace-repository: ghcr.io/${{ github.repository_owner }}/omnibot
    permissions:
      packages: write
      contents: read
